# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:  [ master, development, experimental, osb* ]
  pull_request:
    branches:  [ master, development, experimental, osb* ]

jobs:
  build_and_test:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '16', '17', '19', '21' ]
        runs-on: [ubuntu-latest, macos-latest, windows-latest ]

    name: Test on Java ${{ matrix.Java }} on ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'temurin'

    - name: Install org.neuroml.model.injectingplugin
      env:
        main_repo_branch: ${GITHUB_REF_NAME}
      if: ${{ matrix.runs-on != 'windows-latest' }}
      run: |
        export main_repo_branch=${{env.main_repo_branch}}
        if [[ ${main_repo_branch} != "master" && ${main_repo_branch} != "development" && ${main_repo_branch} != "experimental" && ${main_repo_branch} != *"osb"* ]]; then main_repo_branch=development ; fi
        echo Using branch $main_repo_branch
        git clone https://github.com/NeuroML/org.neuroml.model.injectingplugin.git
        cd org.neuroml.model.injectingplugin
        git checkout $main_repo_branch
        mvn install
        cd ..

        # Install and test this repo with Maven
        mvn install
        mvn dependency:tree

    - name: Install org.neuroml.model.injectingplugin (Win)
      if: ${{ matrix.runs-on == 'windows-latest' }}
      run: |
        echo "Using branch $env:GITHUB_REF_NAME"
        $env:main_repo_branch=$env:GITHUB_REF_NAME
        if ( $env:main_repo_branch -ne "master" -and $env:main_repo_branch -ne "development" -and $env:main_repo_branch -ne "experimental" -and $env:main_repo_branch -notlike '*osb*' ) { $env:main_repo_branch="development" }
        echo "Using branch $env:main_repo_branch..."
        git clone https://github.com/NeuroML/org.neuroml.model.injectingplugin.git
        cd org.neuroml.model.injectingplugin
        git checkout $env:main_repo_branch
        mvn install
        cd ..

        # Install and test this repo with Maven
        mvn install
        mvn dependency:tree
